#Install required packages
if(!require(mirt)){install.packages("mirt")}
if(!require(ItemResponseTrees)){install.packages("ItemResponseTrees")}
if(!require(tidyverse)){install.packages("tidyverse")}
if(!require(mixRasch)){install.packages("mixRasch")}
if(!require(future)){install.packages("future")}
if(!require(listenv)){install.packages("listenv")}
if(!require(simsalapar)){install.packages("simsalapar")}
if(!require(irtrees)){install.packages("irtrees")}
if(!require(reshape)){install.packages("reshape")}
if(!require(microbenchmark)){install.packages("microbenchmark")}
if(!require(future.apply)){install.packages("future.apply")}
if(!require(TAM)){install.packages("TAM")}
if(!require(lavaan)){install.packages("lavaan")}
if(!require(PCMRS)){install.packages("PCMRS")}
if(!require(shiny)){install.packages("shiny")}
#install.packages("remotes")
#remotes::install_github("hplieninger/ItemResponseTrees")
#if(!require(installr)){install.packages("installr")}
#updateR()

#Initialize RNG
rnorm(1)

#Make custom item functions for Tree model, since mirt does not support the 
#model for node 2 and node 3 per default
#Custom item function for Node 2
name <- 'Node2TreePL'
par <- c(a1 = 1, a2 = 1, d = 0)
est <- c(TRUE, TRUE, TRUE)
P.Node2TreePL <- function(par,Theta, ncat){
  a1 <- par[1]
  a2 <- par[2]
  d <- par[3]
  P1 <- exp((a1 * Theta[,1] - a2 * Theta[,2] + d)) /
    (1 + exp((a1 * Theta[,1] - a2 * Theta[,2] + d)))
  cbind(1-P1, P1)
}
Node2TreePL <- createItem(name, par=par, est=est, P=P.Node2TreePL, 
                          derivType = 'symbolic', derivType.hss = 'symbolic')

#Custom item function for Node 3
name <- 'Node3TreePL'
par <- c(a1 = 1, a2 = 1, d = 0)
est <- c(TRUE, TRUE, TRUE)
P.Node3TreePL <- function(par,Theta, ncat){
  a1 <- par[1]
  a2 <- par[2]
  d <- par[3]
  P1 <- exp((a1 * Theta[,1] + a2 * Theta[,2] + d)) /
    (1 + exp((a1 * Theta[,1] + a2 * Theta[,2] + d)))
  cbind(1-P1, P1)
}
Node3TreePL <- createItem(name, par=par, est=est, P=P.Node3TreePL,
                          derivType = 'symbolic', derivType.hss = 'symbolic')

#Create function to generate multigroup data under GPCM, MNRM and IRTree. Note 
#that the GPCM is generated as a MNRM with s = c(0,1,2,...) and setting the ERS 
#mean to 0 with sd of 0. PCM can be generated by also setting alphas to 1.

#Inputs: 
#gen_model: Model that generates the data. Can be "MNRM-Falk" or "IRTree-M"
#Nitems: Number of items to generate
#alpha: alpha parameters for the MNRM or GPCM
#thresholds: item threshold parameters for MNRM or GPCM
#N: Sample size per group
#categories: Number of item categories
#groups: Number of groups
#theta_df: Data frame specifying the mean and standard deviation of the theta
#and ERS dimensions. Every row is a group. First column is the mean of 
#the first dimension, second colimn is the sd of the first dimension, etc.
#estimator: How mirt estimates the model. MHRM, EM and QMCEM are supported
#node1pars: Item parameters of IRTree node 1 in the order a1, a2, b. Same for
#node2pars and node3pars

#Outputs
#A list containing the item parameters and fit indices for the GPCM, MNRM and
#IRTree models. In addition, individual trait estimates, true traits and the 
#seed used in data generation are returned
generate <- function(gen_model = "MNRM-Falk", Nitems = 10, alpha = c(1,1), 
                     thresholds = c(-1, 0, 1),
                     N = 100, categories = 4, groups = 1, theta_df,
                     estimator = "EM", 
                     node1pars = matrix(rep(c(1, 0, 0), 10),
                                        nrow = 10, ncol = 3), 
                     node2pars = matrix(rep(c(1, 0, 0), 10),
                                        nrow = 10, ncol = 3), 
                     node3pars = matrix(rep(c(1, 0, 0), 10),
                                        nrow = 10, ncol = 3),
                     ev_IRTree = TRUE, ev_GPCM = TRUE){
  
  #Save seed
  seed <- .Random.seed
  
  #Determine which groups should have their latent means and variances freely
  #estimated. For now, every group except group 1.
  Freegroups <- 2:groups
  
  #Generate matrices to store observed answers and group membership in
  obs_mat <- matrix(rep(NA, N*groups*Nitems), ncol = Nitems)
  obs_mat <- cbind(obs_mat, rep(NA, N*groups))
  theta_store <- matrix(NA, nrow = N*groups, ncol = 2)
  
  #Confirmatory MNRM by Falk and Cai (2016) data generation. Equal to PCM if 
  #alpha is 1 and s_gen = c(0,1,2,...).
  if(gen_model == "MNRM-Falk"){
    
    #Generate s matrix
    s_gen <- matrix(0:(categories - 1), nrow = 1)
    
    #Generate ERS scoring matrix
    ers_mat <- matrix(rep(0, categories), nrow = 1)
    ers_mat[,1] <- ers_mat[,length(ers_mat)] <- 1
    
    #Combine ERS and ORS matrices
    s_gen <- rbind(s_gen, ers_mat)
    
    #initialize category probability, observed answer, newalpha and theta 
    #matrices
    newalpha <- matrix(rep(NA, categories * nrow(s_gen)), ncol = categories)
    cat_prob <- matrix(rep(NA, categories*N), ncol = categories)
    
    for(g in 1:groups){
      
      #Draw participant ability from normal distribution with means and standard
      #deviations as specified in theta_df
      theta <- rnorm(N, mean = theta_df$theta_mean[g], 
                     sd = theta_df$theta_sd[g])
      
      #Draw participant ERS score from normal distribution with means and sd's
      #as specified in theta_df
      theta_ersmrs <- rnorm(N, mean = theta_df$ers_mean[g], 
                            sd = theta_df$ers_sd[g])
      
      #Combine into single matrix
      theta <- cbind(theta, theta_ersmrs)
      
      #Create a range of item difficulties from the mean for a more realistic test
      difficulty <- seq(from =  -0.5, to = 0.5, length = Nitems)
      
      
      for(j in 1:Nitems){
        
        #Convert item thresholds to item intercepts
        item_threshold <- thresholds - difficulty[j]
        int_2 <- -item_threshold[1] * alpha[1]
        int_3 <- int_2 - item_threshold[2] * alpha[1]
        int_4 <- int_3 - item_threshold[3] * alpha[1]
        intercept <- c(0, int_2, int_3, int_4)
        
        #Calculate the new item slope parameters based on the a priori s matrices
        newalpha <- alpha * s_gen
        
        #Calculate category probabilities
        numerator <- exp(apply(theta, 1, "%*%", newalpha) + intercept)
        denominator <- colSums(numerator)
        cat_prob <- t(numerator)/denominator
        
        #Convert probabilities into observed answers
        cat_prob_list <- split(cat_prob, row(cat_prob))
        obs_ans <- sapply(cat_prob_list, 
                          function(x)sample(1:categories, 1, replace = TRUE, prob = x),
                          simplify = TRUE)
        
        #Assign observed answers to observed answers matrix
        obs_mat[(1 + (g-1) * N):(N * g), j] <- obs_ans
      }
      
      #Store group membership in obs_mat matrix
      obs_mat[(1 + (g-1) * N):(N * g), Nitems + 1] <- g
      
      #Store theta in theta_store
      theta_store[(1 + (g-1) * N): (N * g), ] <- theta
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    #Data generation under IRTree multidimensional model
  } else if (gen_model == "IRTree-M"){
    for(g in 1:groups){
      
      #Draw substantive and ERS scores from normal distribution with mean and
      #sd specified in theta_df
      theta <- rnorm(N, mean = theta_df$theta_mean[g],
                     sd = theta_df$theta_sd[g])
      theta_e <- rnorm(N,mean = theta_df$ers_mean[g], 
                       sd = theta_df$ers_sd[g])
      
      #Store theta in theta_store
      theta_store[(1 + (g-1) * N): (N * g), ] <- cbind(theta, theta_e)
      
      #Calculates 1 to N, then N+1 to N * 2, etc. Used to indicate which rows
      #of obs_mat to write answers to
      groupmembers <- (1 + (g - 1) * N):(N * g)
      
      for(j in 1:Nitems){
        #IRTree category probability calculation
        #Node 1: Choose between agree or disagree
        score <- exp(node1pars[j,1] * theta + node1pars[j,3])/
          (1+exp(node1pars[j,1] * theta + node1pars[j,3]))
        score <- matrix(c(score, 1 - score), nrow = N)
        
        #Mode 2: Choose between extreme or non-extreme disagreeing
        score2 <- exp(node2pars[j,1] * theta - node2pars[j,2] * theta_e + node2pars[j,3])/
          (1+exp(node2pars[j,1] * theta - node2pars[j,2] * theta_e + node2pars[j,3]))
        score2 <- matrix(c(score2, 1-score2), nrow = N)
        
        #Node 3: Choose between extreme or non-extreme agreeing
        score3 <- exp(node3pars[j,2] * theta_e + node3pars[j,1] * theta + node3pars[j,3])/
          (1+exp(node3pars[j,2] * theta_e + node3pars[j,1] * theta + node3pars[j,3]))
        score3 <- matrix(c(score3, 1-score3), nrow = N)
        
        #Calculate probabilites of participant answering a category for every
        #participant
        cat_prob_tree <- matrix(NA, nrow = N, ncol = categories)
        cat_prob_tree[,1] <- score[,2] * score2[,2]
        cat_prob_tree[,2] <- score[,2] * score2[,1]
        cat_prob_tree[,3] <- score[,1] * score3[,2]
        cat_prob_tree[,4] <- score[,1] * score3[,1]
        
        #Convert probabilities to actual answers
        cat_prob_list <- split(cat_prob_tree, row(cat_prob_tree))
        obs_mat[groupmembers,j] <- sapply(cat_prob_list, function(x)sample(1:4, 1, 
                                                                           replace = TRUE, prob = x),
                                          simplify = TRUE)
      }
      #Add group membership to obs_mat
      obs_mat[groupmembers,(Nitems + 1)] <- g
    }
    
  } else {
    stop("Data generating model is not correctly specified. Please specify one 
    of the following models for gen_model argument:
         1. MNRM-Falk
         2. IRTree-M")
  }
  
  colnames(theta_store) <- c("Theta", "ERS")
  
  #MNRM evaluation
  #Generate s matrix
  s_gen <- matrix(0:(categories - 1), nrow = 1)
  
  #Generate ERS scoring matrix
  ers_mat <- matrix(rep(0, categories), nrow = 1)
  ers_mat[,1] <- ers_mat[,length(ers_mat)] <- 1
  
  #Combine ORS and ERS matrix
  s_gen <- rbind(s_gen, ers_mat)
  
  
  s_mirt <- vector(mode = "list", length = Nitems)
  items <- 1:Nitems
  #Generate s_mirt matrix to evaluate model
  for(j in 1:Nitems){
    s_mirt[[j]] <- t(s_gen)
    
    #Check if all items actually have 4 categories. If not, shorten the s_gen
    #matrix
    if(length(table(obs_mat[,j])) < 4){
      s_mirt[[j]] <- t(s_gen[,1:3])
      s_mirt[[j]][3,2] <- 1
      items <- items[-j]
    }
  }
  
  #Make sure items have names for mirt
  itemnames <- paste0("item", 1:Nitems)
  colnames(obs_mat) <- c(itemnames, "group")
  
  #Generate mirt model syntax. All dimensions load on all items. In addition,
  #all items are set to be  equal across groups. Covariance between
  #theta and ERS is freely estimated. Covariances and means of latent dimensions
  #in all groups except group 1 are freely estimated.
  modelstart <- paste0("Theta = 1-", Nitems, "
                ", "ERS = 1-", Nitems, "
                CONSTRAINB = (1-", Nitems, ", a1), (1-", Nitems, ", a2), (1-",
                       Nitems, ", d1), (1-", Nitems, ", d2)", ",", paste0("(", items, ", d3)",
                                                                          collapse = ","), "
                ", "FREE = (GROUP, COV_21)", "
                ")
  
  modelend <- paste0( "FREE [",Freegroups, "] = (GROUP, COV_11)", "
        ", "FREE [",Freegroups, "] = (GROUP, COV_22)", "
        ", "FREE [",Freegroups, "] = (GROUP, MEAN_1)", "
        ", "FREE [",Freegroups, "] = (GROUP, MEAN_2)", " 
        ", collapse = "")
  
  model <- paste0(rbind(modelstart, modelend), collapse = "")
  
  #Set these variables to global scale so they get properly overridden by
  #other variables in the trycatch function
  MNRM_small <<- NA
  MNRM_est_traits <<- NA
  
  #Try specified estimation first. If this fails, try QMCEM estimation
  tryCatch(
    expr = {
      MNRM_mod <- multipleGroup(obs_mat[,1:Nitems],
                                group = factor(obs_mat[,(Nitems + 1)]),
                                model = model,
                                itemtype = "gpcm",
                                method = estimator,
                                gpcm_mats = s_mirt,
                                technical = list(NCYCLES = 4000))
      
      #Save results
      itempars_1 <- itempars_2 <- vector(mode = "list", length = (Nitems + 1))
      for(i in 1:(Nitems + 1)){
        itempars_1[[i]] <- MNRM_mod@ParObjects[["pars"]][[1]]@ParObjects[["pars"]][[i]]@par
        itempars_2[[i]] <- MNRM_mod@ParObjects[["pars"]][[2]]@ParObjects[["pars"]][[i]]@par
      }
      
      MNRM_small <- vector(mode = "list", length = 3)
      MNRM_small[[1]] <- MNRM_mod@Fit
      MNRM_small[[2]] <- itempars_1
      MNRM_small[[3]] <- itempars_2
      names(MNRM_small) <- c("Fit", "Group1pars", "Group2pars")
      MNRM_small <<- MNRM_small
      
      #Estimate individual scores
      MNRM_est_traits <<- fscores(MNRM_mod)
    }, 
    error = function(e){
      MNRM_mod <- multipleGroup(obs_mat[,1:Nitems],
                                group = factor(obs_mat[,(Nitems + 1)]),
                                model = model,
                                itemtype = "gpcm",
                                method = "QMCEM",
                                gpcm_mats = s_mirt,
                                technical = list(NCYCLES = 4000))
      
      itempars_1 <- itempars_2 <- vector(mode = "list", length = (Nitems + 1))
      for(i in 1:(Nitems + 1)){
        itempars_1[[i]] <- MNRM_mod@ParObjects[["pars"]][[1]]@ParObjects[["pars"]][[i]]@par
        itempars_2[[i]] <- MNRM_mod@ParObjects[["pars"]][[2]]@ParObjects[["pars"]][[i]]@par
      }
      
      MNRM_small <- vector(mode = "list", length = 3)
      MNRM_small[[1]] <- MNRM_mod@Fit
      MNRM_small[[2]] <- itempars_1
      MNRM_small[[3]] <- itempars_2
      names(MNRM_small) <- c("Fit", "Group1pars", "Group2pars")
      MNRM_small <<- MNRM_small
      
      MNRM_est_traits <<- fscores(MNRM_mod)
    }
  )
  
  
  #IRTree evaluation
  if(ev_IRTree == TRUE){
    #Convert observed answers to IRTree pseudo item format
    tree_dat <- matrix(NA, nrow = N*groups, ncol = Nitems * (categories - 1))
    start_val_d1 <- start_val_d2 <- rep(NA, Nitems)
    for(i in 1:Nitems){
      tree_dat[obs_mat[,i] <= 2, (i-1)*3 +1] <- 0 
      tree_dat[obs_mat[,i] >= 3, (i-1)*3 +1] <- 1
      
      tree_dat[obs_mat[,i] == 2, (i-1)*3 + 2] <- 1 
      tree_dat[obs_mat[,i] == 1, (i-1)*3 + 2] <- 0
      
      tree_dat[obs_mat[,i] == 3, (i-1)*3 + 3] <- 0 
      tree_dat[obs_mat[,i] == 4, (i-1)*3 + 3] <- 1 
    }
    
    #Determine start value of intercept based on observed proportion correct.
    #Speeds up estimation
    start_val_d1 <- table(tree_dat[,(ncol(tree_dat)/2 + 1)])[2]/
      table(tree_dat[, (ncol(tree_dat)/2 + 1)])[1]
    start_val_d2 <- table(tree_dat[,(ncol(tree_dat)/2 + 2)])[2]/
      table(tree_dat[, (ncol(tree_dat)/2 + 2)])[1]
    
    if(start_val_d1 < 1){
      start_val_d1 <- -start_val_d1
    }
    if(start_val_d2 < 1){
      start_val_d2 <- -start_val_d2
    }
    
    #Evaluate IRTree model using mirt
    #Assign itemnodes names for MIRT
    items <- sort(rep(1:Nitems, 3))
    items <- paste0("item", items)
    nodes <- 1:3
    nodes <- rep(paste0("node", nodes), Nitems)
    colnames(tree_dat) <- paste0(items, nodes)
    
    #Create group membership vector
    group <- c(rep(1, N), rep(2, N))
    
    #Determine which item nodes ERS loads on (second and third nodes). In addition,
    #determine which node alphas are constrained to -1 or 1 respectively.
    ersloadings <- rep(NA, (Nitems * 2))
    node1alpha <- node2alpha <- node3alpha <- rep(NA, Nitems)
    for(i in 1:Nitems){
      ersloadings[(i-1)*2+1] <- (i-1)*3+2
      ersloadings[(i-1)*2+2] <- (i-1)*3+3
      node1alpha[i] <- (i-1)*3+1
      node2alpha[i] <- (i-1)*3+2
      node3alpha[i] <- (i-1)*3+3
    }
    
    #Specify itemtypes for mirt
    itemtypes <- rep(c("2PL", "Node2TreePL", "Node3TreePL"), Nitems)
    
    #adjust if any item has no participants in that node
    tree_dat_adj <- tree_dat
    for(i in 1:ncol(tree_dat)){
      if(length(table(tree_dat[,i])) < 2){
        tree_dat_adj <- tree_dat_adj[,-i]
        
        ers_shift <- which(ersloadings == i)
        ersloadings <- ersloadings[-ers_shift]
        ersloadings[ers_shift:length(ersloadings)] <- 
          ersloadings[ers_shift:length(ersloadings)] - 1
        
        itemtypes <- itemtypes[-i]
        
        constraints_shift <- ceiling(i/3)
        node2alpha <- node2alpha[-constraints_shift]
        node3alpha <- node3alpha[-constraints_shift]
        node2alpha[constraints_shift : length(node2alpha)] <-
          node2alpha[constraints_shift : length(node2alpha)] - 1
        node3alpha[constraints_shift : length(node3alpha)] <- 
          node3alpha[constraints_shift : length(node3alpha)] - 1
        
      }
    }
    #Triple number of items for tree model
    treeNitems <- ncol(tree_dat_adj)
    
    #Generate mirt syntax. Theta loads on all item nodes, ERS loads on item nodes
    #2 and 3. All items are constrained equal across groups. a1 parameters
    #are set to -1 and 1 for node 2 and node 3 respectively. Covariance between
    #ERS and theta is freely estimated. Latent means and covariances are freely
    #estimated in every group except group 1.
    
    #Constraints
    model <- paste0("Theta = 1-", treeNitems, "
                ", "ERS = ", paste0(ersloadings, collapse = ","), "
                CONSTRAINB = (1-", treeNitems, ", a1), (1-", treeNitems, ", a2), (1-",
                    treeNitems, ", d)", "
                ", "CONSTRAIN = ", paste0("(",node2alpha, ",", node3alpha, ", a1)", collapse = ","), ",", "
                     ", paste0("(",node2alpha, ",", node3alpha, ", a2)", collapse = ","), "
                     ", "START = (", paste0(node2alpha, collapse = ","), ", d, ", start_val_d1, "), (",
                    paste0(node3alpha, collapse = ","), ", d, ", start_val_d2, ") ", "
                    ")
    
    model2 <- paste0("FREE = (GROUP, COV_21)", "
                     ", "FREE [",Freegroups, "] = (GROUP, COV_11)", "
        ", "FREE [",Freegroups, "] = (GROUP, COV_22)", "
        ", "FREE [",Freegroups, "] = (GROUP, MEAN_1)", "
        ", "FREE [",Freegroups, "] = (GROUP, MEAN_2)",
                     collapse = "")
    
    model <- paste0(model, model2, collapse = "")
    
    Tree_small <<- NA
    Tree_est_traits <<- NA
    
    tryCatch({
      #Evaluate model using MIRT with supplied estimator. If this fails. try
      #QMCEM estimation
      Tree_mod <- multipleGroup(tree_dat_adj,
                                model = model,
                                method = estimator,
                                itemtype = itemtypes,
                                group = factor(group),
                                technical = list(NCYCLES = 4000),
                                customItems=list(Node2TreePL = Node2TreePL,
                                                 Node3TreePL = Node3TreePL))
      
      itempars_1 <- itempars_2 <- vector(mode = "list", length = (treeNitems + 1))
      for(i in 1:(treeNitems + 1)){
        itempars_1[[i]] <- Tree_mod@ParObjects[["pars"]][[1]]@ParObjects[["pars"]][[i]]@par
        itempars_2[[i]] <- Tree_mod@ParObjects[["pars"]][[2]]@ParObjects[["pars"]][[i]]@par
      }
      
      Tree_small <- vector(mode = "list", length = 3)
      Tree_small[[1]] <- Tree_mod@Fit
      Tree_small[[2]] <- itempars_1
      Tree_small[[3]] <- itempars_2
      names(Tree_small) <- c("Fit", "Group1pars", "Group2pars")
      Tree_small <<- Tree_small
      
      Tree_est_traits <<- fscores(Tree_mod)
    }, 
    error = function(e){
      Tree_mod <- multipleGroup(tree_dat_adj,
                                model = model,
                                method = "QMCEM",
                                itemtype = itemtypes,
                                group = factor(group),
                                technical = list(NCYCLES = 4000),
                                customItems=list(Node2TreePL = Node2TreePL,
                                                 Node3TreePL = Node3TreePL))
      
      itempars_1 <- itempars_2 <- vector(mode = "list", length = (treeNitems + 1))
      for(i in 1:(treeNitems + 1)){
        itempars_1[[i]] <- Tree_mod@ParObjects[["pars"]][[1]]@ParObjects[["pars"]][[i]]@par
        itempars_2[[i]] <- Tree_mod@ParObjects[["pars"]][[2]]@ParObjects[["pars"]][[i]]@par
      }
      
      Tree_small <- vector(mode = "list", length = 3)
      Tree_small[[1]] <- Tree_mod@Fit
      Tree_small[[2]] <- itempars_1
      Tree_small[[3]] <- itempars_2
      names(Tree_small) <- c("Fit", "Group1pars", "Group2pars")
      Tree_small <<- Tree_small
      
      Tree_est_traits <<- fscores(Tree_mod)
      
      }
    )
  } else{
    Tree_small <<- NA
    Tree_est_traits <<- NA
  }
  
  if(ev_GPCM == TRUE){
    tryCatch({
      #GPCM estimation. Theta loads on all items. Slopes and intercepts are 
      #constrained equal across groups. Means and variances of latent trait are
      #freely estimated outside of group 1.
      GPCM_mod <- multipleGroup(obs_mat[,1:Nitems],
                                group = factor(obs_mat[, (Nitems + 1)]),
                                model = paste0("Theta = 1-", Nitems),
                                itemtype = "gpcm",
                                method = estimator,
                                invariance = c("free_mean", "free_var", "slopes",
                                               "intercepts"),
                                technical = list(NCYCLES = 4000))
      
      itempars_1 <- itempars_2 <- vector(mode = "list", length = (Nitems + 1))
      for(i in 1:(Nitems + 1)){
        itempars_1[[i]] <- GPCM_mod@ParObjects[["pars"]][[1]]@ParObjects[["pars"]][[i]]@par
        itempars_2[[i]] <- GPCM_mod@ParObjects[["pars"]][[2]]@ParObjects[["pars"]][[i]]@par
      }
      
      GPCM_small <- vector(mode = "list", length = 3)
      GPCM_small[[1]] <- GPCM_mod@Fit
      GPCM_small[[2]] <- itempars_1
      GPCM_small[[3]] <- itempars_2
      
      names(GPCM_small) <- c("Fit", "Group1pars", "Group2pars")
      GPCM_small <<- GPCM_small
      
      GPCM_est_traits <<- fscores(GPCM_mod)
    }, 
    error = function(e){
      GPCM_small <<- NA
      GPCM_est_traits <<- NA}
    )
  } else{
    GPCM_small <<- NA
    GPCM_est_traits <<- NA
  }
  
  #Combine MNRM, IRTree and GPCM outcomes as a list and return them. In addition,
  #return item parameters
  outcome <- list(MNRM = MNRM_small, IRTree = Tree_small, GPCM = GPCM_small,
                  True_traits = theta_store, MNRM_traits = MNRM_est_traits,
                  Tree_traits = Tree_est_traits, GPCM_traits = GPCM_est_traits,
                  seed = seed)
  return(outcome)
}


#Obtain IRTree parameters from MNRM parameters
theta_df <- data.frame(theta_mean = c(0,0), theta_sd = c(1,1),
                       ers_mean = c(0, 0), ers_sd = c(1,1))

set.seed(112)
test1 <- generate(gen_model = "MNRM-Falk", N = 500000,
                  categories = 4, groups = 2,
                  theta_df = theta_df, Nitems = 10,
                  alpha = c(1.5, 1.5), thresholds = c(-1, 0, 1))

test2 <- generate(gen_model = "MNRM-Falk", N = 500000,
                  categories = 4, groups = 2,
                  theta_df = theta_df, Nitems = 10,
                  alpha = c(1.5, 1.5), thresholds = c(0, 1, 2))

test3 <- generate(gen_model = "MNRM-Falk", N = 500000,
                  categories = 4, groups = 2,
                  theta_df = theta_df, Nitems = 20,
                  alpha = c(1.5, 1.5), thresholds = c(-1, 0, 1))

test4 <- generate(gen_model = "MNRM-Falk", N = 500000,
                  categories = 4, groups = 2,
                  theta_df = theta_df, Nitems = 20,
                  alpha = c(1.5, 1.5), thresholds = c(0, 1, 2))

tree_node1 <- tree_node1_dif <- tree_node2 <- tree_node2_dif <-
  tree_node3 <- tree_node3_dif <- matrix(NA, nrow = 10, ncol = 3)

tree_node1_20 <- tree_node1_dif_20 <- tree_node2_20 <- tree_node2_dif_20 <-
  tree_node3_20 <- tree_node3_dif_20 <- matrix(NA, nrow = 20, ncol = 3)
for(i in 1:10){
  tree_node1[i,] <- test1[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 1]][1:3]
  tree_node2[i,] <- test1[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 2]]
  tree_node3[i,] <- test1[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 3]]
  tree_node1_dif[i,] <- test2[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 1]][1:3]
  tree_node2_dif[i,] <- test2[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 2]]
  tree_node3_dif[i,] <- test2[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 3]]
}

for(i in 1:20){
  tree_node1_20[i,] <- test3[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 1]][1:3]
  tree_node2_20[i,] <- test3[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 2]]
  tree_node3_20[i,] <- test3[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 3]]
  tree_node1_dif_20[i,] <- test4[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 1]][1:3]
  tree_node2_dif_20[i,] <- test4[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 2]]
  tree_node3_dif_20[i,] <- test4[["IRTree"]][["Group1pars"]][[(i-1) * 3 + 3]]
}

################################################################################
#GPCM generated data
################################################################################
#Generate data in chunks of 100 and save inbetween
plan(multisession)
list <- vector(mode = "list", length = 100)
theta_df <- data.frame(theta_mean = c(0,0), theta_sd = c(1,1),
                       ers_mean = c(0, 0), ers_sd = c(0,0))
test_GPCM_average_10_1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 10, alpha = c(1.5,1.5), 
                                        thresholds = c(-1, 0, 1), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 1)

save.image("Control1.RData")

test_GPCM_average_10_2 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 10, alpha = c(1.5,1.5), 
                                        thresholds = c(-1, 0, 1), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 2)

save.image("Control2.RData")

test_GPCM_average_10_3 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 10, alpha = c(1.5,1.5), 
                                        thresholds = c(-1, 0, 1), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 3)

save.image("Control3.RData")

test_GPCM_average_10_4 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 10, alpha = c(1.5,1.5), 
                                        thresholds = c(-1, 0, 1), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 4)

save.image("Control4.RData")

test_GPCM_average_10_5 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 10, alpha = c(1.5,1.5), 
                                        thresholds = c(-1, 0, 1), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 29)
save.image("Control5.RData")

test_GPCM_difficult_10_1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                          Nitems = 10, alpha = c(1.5,1.5), 
                                          thresholds = c(0, 1, 2), N = 500, 
                                          categories = 4, groups = 2, 
                                          theta_df = theta_df,
                                          estimator = "EM", future.seed = 30)

save.image("Control6.RData")

test_GPCM_difficult_10_2 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                          Nitems = 10, alpha = c(1.5,1.5), 
                                          thresholds = c(0, 1, 2), N = 500, 
                                          categories = 4, groups = 2, 
                                          theta_df = theta_df,
                                          estimator = "EM", future.seed = 31)

save.image("Control7.RData")

test_GPCM_difficult_10_3 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                          Nitems = 10, alpha = c(1.5,1.5), 
                                          thresholds = c(0, 1, 2), N = 500, 
                                          categories = 4, groups = 2, 
                                          theta_df = theta_df,
                                          estimator = "EM", future.seed = 32)

save.image("Control8.RData")

test_GPCM_difficult_10_4 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                          Nitems = 10, alpha = c(1.5,1.5), 
                                          thresholds = c(0, 1, 2), N = 500, 
                                          categories = 4, groups = 2, 
                                          theta_df = theta_df,
                                          estimator = "EM", future.seed = 33)

save.image("Control9.RData")

test_GPCM_difficult_10_5 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                          Nitems = 10, alpha = c(1.5,1.5), 
                                          thresholds = c(0, 1, 2), N = 500, 
                                          categories = 4, groups = 2, 
                                          theta_df = theta_df,
                                          estimator = "EM", future.seed = 34)
save.image("Control10.RData")

test_GPCM_average_20_1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 20, alpha = c(1.5,1.5), 
                                        thresholds = c(-1, 0, 1), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 35)

save.image("Control11.RData")

test_GPCM_average_20_2 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 20, alpha = c(1.5,1.5), 
                                        thresholds = c(-1, 0, 1), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 36)

save.image("Control12.RData")

test_GPCM_average_20_3 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 20, alpha = c(1.5,1.5), 
                                        thresholds = c(-1, 0, 1), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 37)

save.image("Control13.RData")

test_GPCM_average_20_4 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 20, alpha = c(1.5,1.5), 
                                        thresholds = c(-1, 0, 1), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 38)

save.image("Control14.RData")

test_GPCM_average_20_5 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 20, alpha = c(1.5,1.5), 
                                        thresholds = c(-1, 0, 1), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 39)
save.image("Control15.RData")

test_GPCM_difficult_20_1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                          Nitems = 10, alpha = c(1.5,1.5), 
                                          thresholds = c(0, 1, 2), N = 500, 
                                          categories = 4, groups = 2, 
                                          theta_df = theta_df,
                                          estimator = "EM", future.seed = 40)

save.image("Control16.RData")

test_GPCM_difficult_20_2 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                          Nitems = 10, alpha = c(1.5,1.5), 
                                          thresholds = c(0, 1, 2), N = 500, 
                                          categories = 4, groups = 2, 
                                          theta_df = theta_df,
                                          estimator = "EM", future.seed = 41)

save.image("Control17.RData")

test_GPCM_difficult_20_3 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                          Nitems = 10, alpha = c(1.5,1.5), 
                                          thresholds = c(0, 1, 2), N = 500, 
                                          categories = 4, groups = 2, 
                                          theta_df = theta_df,
                                          estimator = "EM", future.seed = 42)

save.image("Control18.RData")

test_GPCM_difficult_20_4 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                          Nitems = 10, alpha = c(1.5,1.5), 
                                          thresholds = c(0, 1, 2), N = 500, 
                                          categories = 4, groups = 2, 
                                          theta_df = theta_df,
                                          estimator = "EM", future.seed = 43)

save.image("Control19.RData")

test_GPCM_difficult_20_5 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                          Nitems = 10, alpha = c(1.5,1.5), 
                                          thresholds = c(0, 1, 2), N = 500, 
                                          categories = 4, groups = 2, 
                                          theta_df = theta_df,
                                          estimator = "EM", future.seed = 44)

save.image("Control20.RData")

################################################################################
#MNRM data
################################################################################
#Same as GPCM but generate in chunks of 500
plan(multisession)
list <- vector(mode = "list", length = 500)

theta_df <- data.frame(theta_mean = c(0,0), theta_sd = c(1,1),
                       ers_mean = c(0, 0), ers_sd = c(1,1))

test_MNRM_average_10 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                      Nitems = 10, alpha = c(1.5,1.5), 
                                      thresholds = c(-1, 0, 1), N = 500, 
                                      categories = 4, groups = 2, 
                                      theta_df = theta_df,
                                      estimator = "EM", future.seed = 5)

test_MNRM_average_20 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                      Nitems = 20, alpha = c(1.5,1.5), 
                                      thresholds = c(-1, 0, 1), N = 500, 
                                      categories = 4, groups = 2, 
                                      theta_df = theta_df,
                                      estimator = "EM", future.seed = 6)

test_MNRM_difficult_10 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 10, alpha = c(1.5,1.5), 
                                        thresholds = c(0, 1, 2), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 7)

test_MNRM_difficult_20 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                        Nitems = 20, alpha = c(1.5,1.5), 
                                        thresholds = c(0, 1, 2), N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 8)

theta_df <- data.frame(theta_mean = c(0,0), theta_sd = c(1,1),
                       ers_mean = c(0, 1), ers_sd = c(1,1))

test_MNRM_average_10_ERS_1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                            Nitems = 10, alpha = c(1.5,1.5), 
                                            thresholds = c(-1, 0, 1), N = 500, 
                                            categories = 4, groups = 2, 
                                            theta_df = theta_df,
                                            estimator = "EM", future.seed = 9)

test_MNRM_average_20_ERS_1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                            Nitems = 20, alpha = c(1.5,1.5), 
                                            thresholds = c(-1, 0, 1), N = 500, 
                                            categories = 4, groups = 2, 
                                            theta_df = theta_df,
                                            estimator = "EM", future.seed = 10)

test_MNRM_difficult_10_ERS_1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                              Nitems = 10, alpha = c(1.5,1.5), 
                                              thresholds = c(0, 1, 2), N = 500, 
                                              categories = 4, groups = 2, 
                                              theta_df = theta_df,
                                              estimator = "EM", future.seed = 11)

test_MNRM_difficult_20_ERS_1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                              Nitems = 20, alpha = c(1.5,1.5), 
                                              thresholds = c(0, 1, 2), N = 500, 
                                              categories = 4, groups = 2, 
                                              theta_df = theta_df,
                                              estimator = "EM", future.seed = 12)

theta_df <- data.frame(theta_mean = c(0,0), theta_sd = c(1,1),
                       ers_mean = c(0, -1), ers_sd = c(1,1))

test_MNRM_average_10_ERS_min1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                               Nitems = 10, alpha = c(1.5,1.5), 
                                               thresholds = c(-1, 0, 1), N = 500, 
                                               categories = 4, groups = 2, 
                                               theta_df = theta_df,
                                               estimator = "EM", future.seed = 13)

test_MNRM_average_20_ERS_min1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                               Nitems = 20, alpha = c(1.5,1.5), 
                                               thresholds = c(-1, 0, 1), N = 500, 
                                               categories = 4, groups = 2, 
                                               theta_df = theta_df,
                                               estimator = "EM", future.seed = 14)

test_MNRM_difficult_10_ERS_min1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                                 Nitems = 10, alpha = c(1.5,1.5), 
                                                 thresholds = c(0, 1, 2), N = 500, 
                                                 categories = 4, groups = 2, 
                                                 theta_df = theta_df,
                                                 estimator = "EM", future.seed = 15)

test_MNRM_difficult_20_ERS_min1 <- future_lapply(list, generate, gen_model = "MNRM-Falk",
                                                 Nitems = 20, alpha = c(1.5,1.5), 
                                                 thresholds = c(0, 1, 2), N = 500, 
                                                 categories = 4, groups = 2, 
                                                 theta_df = theta_df,
                                                 estimator = "EM", future.seed = 16)

save.image(file = "MNRMdata.RData")

################################################################################
#IRTree, 500 reps
################################################################################
plan(multisession)
list <- vector(mode = "list", length = 500)

#No ERS
theta_df <- data.frame(theta_mean = c(0,0), theta_sd = c(1,1),
                       ers_mean = c(0, 0), ers_sd = c(1,1))

test_Tree_average_10 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                      Nitems = 10, node1pars = tree_node1,
                                      node2pars = tree_node2, 
                                      node3pars = tree_node3, N = 500, 
                                      categories = 4, groups = 2, 
                                      theta_df = theta_df,
                                      estimator = "EM", future.seed = 17)
save.image(file = "Treedata.RData")

test_Tree_average_20 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                      Nitems = 20, node1pars = tree_node1_20,
                                      node2pars = tree_node2_20, 
                                      node3pars = tree_node3_20, N = 500, 
                                      categories = 4, groups = 2, 
                                      theta_df = theta_df,
                                      estimator = "EM", future.seed = 18)
save.image(file = "Treedata2.RData")

test_Tree_difficult_10 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                        Nitems = 10, node1pars = tree_node1_dif,
                                        node2pars = tree_node2_dif, 
                                        node3pars = tree_node3_dif, N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 19)
save.image(file = "Treedata3.RData")

test_Tree_difficult_20 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                        Nitems = 20, node1pars = tree_node1_dif_20,
                                        node2pars = tree_node2_dif_20, 
                                        node3pars = tree_node3_dif_20, N = 500, 
                                        categories = 4, groups = 2, 
                                        theta_df = theta_df,
                                        estimator = "EM", future.seed = 20)
save.image(file = "Treedata4.RData")

theta_df <- data.frame(theta_mean = c(0,0), theta_sd = c(1,1),
                       ers_mean = c(0, 1), ers_sd = c(1,1))

test_Tree_average_10_ERS_1 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                            Nitems = 10, node1pars = tree_node1,
                                            node2pars = tree_node2, 
                                            node3pars = tree_node3, N = 500, 
                                            categories = 4, groups = 2, 
                                            theta_df = theta_df,
                                            estimator = "EM", future.seed = 21)
save.image(file = "Treedata5.RData")

test_Tree_average_20_ERS_1 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                            Nitems = 20, node1pars = tree_node1_20,
                                            node2pars = tree_node2_20, 
                                            node3pars = tree_node3_20, N = 500, 
                                            categories = 4, groups = 2, 
                                            theta_df = theta_df,
                                            estimator = "EM", future.seed = 22)
save.image(file = "Treedata6.RData")

test_Tree_difficult_10_ERS_1 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                              Nitems = 10, node1pars = tree_node1_dif,
                                              node2pars = tree_node2_dif, 
                                              node3pars = tree_node3_dif, N = 500, 
                                              categories = 4, groups = 2, 
                                              theta_df = theta_df,
                                              estimator = "EM", future.seed = 23)
save.image(file = "Treedata7.RData")

test_Tree_difficult_20_ERS_1 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                              Nitems = 20, node1pars = tree_node1_dif_20,
                                              node2pars = tree_node2_dif_20, 
                                              node3pars = tree_node3_dif_20, N = 500, 
                                              categories = 4, groups = 2, 
                                              theta_df = theta_df,
                                              estimator = "EM", future.seed = 24)
save.image(file = "Treedata8.RData")

theta_df <- data.frame(theta_mean = c(0,0), theta_sd = c(1,1),
                       ers_mean = c(0, -1), ers_sd = c(1,1))

test_Tree_average_10_ERS_min1 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                               Nitems = 10, node1pars = tree_node1,
                                               node2pars = tree_node2, 
                                               node3pars = tree_node3, N = 500, 
                                               categories = 4, groups = 2, 
                                               theta_df = theta_df,
                                               estimator = "EM", future.seed = 25)
save.image(file = "Treedata9.RData")

test_Tree_average_20_ERS_min1 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                               Nitems = 20, node1pars = tree_node1_20,
                                               node2pars = tree_node2_20, 
                                               node3pars = tree_node3_20, N = 500, 
                                               categories = 4, groups = 2, 
                                               theta_df = theta_df,
                                               estimator = "EM", future.seed = 26)
save.image(file = "Treedata10.RData")

test_Tree_difficult_10_ERS_min1 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                                 Nitems = 10, node1pars = tree_node1_dif,
                                                 node2pars = tree_node2_dif, 
                                                 node3pars = tree_node3_dif, N = 500, 
                                                 categories = 4, groups = 2, 
                                                 theta_df = theta_df,
                                                 estimator = "EM", future.seed = 27)
save.image(file = "Treedata11.RData")

test_Tree_difficult_20_ERS_min1 <- future_lapply(list, generate, gen_model = "IRTree-M",
                                                 Nitems = 20, node1pars = tree_node1_dif_20,
                                                 node2pars = tree_node2_dif_20, 
                                                 node3pars = tree_node3_dif_20, N = 500, 
                                                 categories = 4, groups = 2, 
                                                 theta_df = theta_df,
                                                 estimator = "EM", future.seed = 28)
save.image(file = "Treedata12.RData")

################################################################################
#End of data generation. For analysis, open the analysis script
################################################################################